DROP TABLE NOTICE;

CREATE TABLE NOTICE(
    BNO NUMBER NOT NULL,
    TITLE VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(2000) NOT NULL,
    ID VARCHAR2(20) NOT NULL,
    REGDATE DATE DEFAULT SYSDATE,
    PRIMARY KEY (BNO)
    );
    
DROP SEQUENCE NOTICE_SEQ;
    
CREATE SEQUENCE NOTICE_SEQ
START WITH 1
INCREMENT BY 1;


INSERT INTO NOTICE(BNO, TITLE, CONTENT, ID) VALUES (NOTICE_SEQ.NEXTVAL, '제목입니다', '내용입니다', 'ALL_THE_CAR');

UPDATE NOTICE SET TITLE = '테스트1' WHERE BNO = 1;
UPDATE NOTICE SET ID = 'manager' WHERE BNO = 1;

DELETE FROM NOTICE WHERE BNO = 1;

INSERT INTO NOTICE(BNO, TITLE, CONTENT, ID)
SELECT NOTICE_SEQ.NEXTVAL, TITLE, CONTENT, ID FROM NOTICE;


SELECT  BNO,
        TITLE,
        CONTENT,
        ID,
        REGDATE
FROM (
    SELECT  BNO,
            TITLE,
            CONTENT,
            ID,
            REGDATE,
            ROW_NUMBER() OVER(ORDER BY BNO DESC) AS RNUM
    FROM NOTICE)
WHERE RNUM BETWEEN 1 AND 10
ORDER BY BNO DESC;


SELECT * FROM NOTICE;

COMMIT;
